version: '3'
x-airflow-common:
  &airflow-common
  depends_on:
    postgres:
      condition: service_healthy
    mysql:

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
  mysql:
    image: sakiladb/mysql:8
    volumes:
      - sakila-db-volume:/var/lib/mysql
    ports:
      - 3308:3306
    restart: always
volumes:
  postgres-db-volume:
  sakila-db-volume:

networks:
  default: